# .streamlit/secrets.toml
[connections_dbms]
conn_name = "connections_oracle"
env_name = "pc-driver"

[connections_postgresql]
dialect = "postgresql"
host = "localhost"
port = 5432
database = "palette"
username = "hkcloud"
password = "hkcloud1"
encoding = 'UTF-8'
schemaname = "aikms"

[connections_oracle]
dialect = "oracle"
host = "61.106.19.217"
port = 33389
database = "CDB1"
username = "DPKMAPP"
password = "Kms12#$"
encoding = 'UTF-8'
schemaname= "DPKMAPP"